version: "3.9"
services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./app
    ports:
      - "8888:8888"
    volumes:
      - ./app:/app
      - ./.env:/app/build/.env
    depends_on:
      - database
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'todo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'todo'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'todopass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '13306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: